---
name: PaymentPool
main: blugin\api\paymentpool\PaymentPool
version: 1.4.0
api: [3.16.0]
authors: ['Blugin-team', 'PresentKim']
description: '[API] API plugin that registers and manages several payment plugins'

permissions:
  payment.cmd:
    description: PaymentPool command
    default: op
    children:
      payment.cmd.set:
        description: PaymentPool command - set
        default: op
      payment.cmd.payments:
        description: PaymentPool command - payments
        default: op
      payment.cmd.links:
        description: PaymentPool command - links
        default: op
      payment.cmd.install:
        description: PaymentPool command - install
        default: op
...
